### ISSUE TITLE
关于获取用户token的问题

### ISSUE THREAD

**Issue by ChangFeng2015** [kioyong/yong-security#1]
你好，我有个问题请教您一下，我把项目启动后，swagger提供的Api中注册了个用户，mongo数据库中也可以看到该用户的信息,我在swagger中准备用该用户的身份访问其他Api时，发现需要token，我怎么才能获取到我这个用户的token,才能方便的访问其他的Api

**Comment by kioyong** [comment]
Postman collections link https://www.getpostman.com/collections/27ce38795a2e29ac5294
